<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeatNegotiationStatuses', 'doctrine');

/**
 * BaseSeatNegotiationStatuses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seat_negotiation_statuses_id
 * @property string $display_text
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $SeatNegotiations
 * 
 * @method integer                 getSeatNegotiationStatusesId()    Returns the current record's "seat_negotiation_statuses_id" value
 * @method string                  getDisplayText()                  Returns the current record's "display_text" value
 * @method timestamp               getCreatedAt()                    Returns the current record's "created_at" value
 * @method timestamp               getUpdatedAt()                    Returns the current record's "updated_at" value
 * @method Doctrine_Collection     getSeatNegotiations()             Returns the current record's "SeatNegotiations" collection
 * @method SeatNegotiationStatuses setSeatNegotiationStatusesId()    Sets the current record's "seat_negotiation_statuses_id" value
 * @method SeatNegotiationStatuses setDisplayText()                  Sets the current record's "display_text" value
 * @method SeatNegotiationStatuses setCreatedAt()                    Sets the current record's "created_at" value
 * @method SeatNegotiationStatuses setUpdatedAt()                    Sets the current record's "updated_at" value
 * @method SeatNegotiationStatuses setSeatNegotiations()             Sets the current record's "SeatNegotiations" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSeatNegotiationStatuses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seat_negotiation_statuses');
        $this->hasColumn('seat_negotiation_statuses_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('display_text', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SeatNegotiations', array(
             'local' => 'seat_negotiation_statuses_id',
             'foreign' => 'seat_negotiation_statuses_id'));
    }
}