<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeatNegotiations', 'doctrine');

/**
 * BaseSeatNegotiations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seat_negotiation_id
 * @property integer $proposed_route_id
 * @property integer $seat_negotiation_statuses_id
 * @property integer $carpool_id
 * @property integer $passenger_id
 * @property float $price
 * @property integer $seat_count
 * @property string $pickup_date
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property time $pickup_time
 * @property Routes $Routes
 * @property SeatNegotiationStatuses $SeatNegotiationStatuses
 * @property Carpools $Carpools
 * @property Passengers $Passengers
 * @property Doctrine_Collection $SeatNegotiationMessage
 * @property Doctrine_Collection $Seats
 * 
 * @method integer                 getSeatNegotiationId()            Returns the current record's "seat_negotiation_id" value
 * @method integer                 getProposedRouteId()              Returns the current record's "proposed_route_id" value
 * @method integer                 getSeatNegotiationStatusesId()    Returns the current record's "seat_negotiation_statuses_id" value
 * @method integer                 getCarpoolId()                    Returns the current record's "carpool_id" value
 * @method integer                 getPassengerId()                  Returns the current record's "passenger_id" value
 * @method float                   getPrice()                        Returns the current record's "price" value
 * @method integer                 getSeatCount()                    Returns the current record's "seat_count" value
 * @method string                  getPickupDate()                   Returns the current record's "pickup_date" value
 * @method timestamp               getCreatedAt()                    Returns the current record's "created_at" value
 * @method timestamp               getUpdatedAt()                    Returns the current record's "updated_at" value
 * @method time                    getPickupTime()                   Returns the current record's "pickup_time" value
 * @method Routes                  getRoutes()                       Returns the current record's "Routes" value
 * @method SeatNegotiationStatuses getSeatNegotiationStatuses()      Returns the current record's "SeatNegotiationStatuses" value
 * @method Carpools                getCarpools()                     Returns the current record's "Carpools" value
 * @method Passengers              getPassengers()                   Returns the current record's "Passengers" value
 * @method Doctrine_Collection     getSeatNegotiationMessage()       Returns the current record's "SeatNegotiationMessage" collection
 * @method Doctrine_Collection     getSeats()                        Returns the current record's "Seats" collection
 * @method SeatNegotiations        setSeatNegotiationId()            Sets the current record's "seat_negotiation_id" value
 * @method SeatNegotiations        setProposedRouteId()              Sets the current record's "proposed_route_id" value
 * @method SeatNegotiations        setSeatNegotiationStatusesId()    Sets the current record's "seat_negotiation_statuses_id" value
 * @method SeatNegotiations        setCarpoolId()                    Sets the current record's "carpool_id" value
 * @method SeatNegotiations        setPassengerId()                  Sets the current record's "passenger_id" value
 * @method SeatNegotiations        setPrice()                        Sets the current record's "price" value
 * @method SeatNegotiations        setSeatCount()                    Sets the current record's "seat_count" value
 * @method SeatNegotiations        setPickupDate()                   Sets the current record's "pickup_date" value
 * @method SeatNegotiations        setCreatedAt()                    Sets the current record's "created_at" value
 * @method SeatNegotiations        setUpdatedAt()                    Sets the current record's "updated_at" value
 * @method SeatNegotiations        setPickupTime()                   Sets the current record's "pickup_time" value
 * @method SeatNegotiations        setRoutes()                       Sets the current record's "Routes" value
 * @method SeatNegotiations        setSeatNegotiationStatuses()      Sets the current record's "SeatNegotiationStatuses" value
 * @method SeatNegotiations        setCarpools()                     Sets the current record's "Carpools" value
 * @method SeatNegotiations        setPassengers()                   Sets the current record's "Passengers" value
 * @method SeatNegotiations        setSeatNegotiationMessage()       Sets the current record's "SeatNegotiationMessage" collection
 * @method SeatNegotiations        setSeats()                        Sets the current record's "Seats" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSeatNegotiations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seat_negotiations');
        $this->hasColumn('seat_negotiation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('proposed_route_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('seat_negotiation_statuses_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('carpool_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('passenger_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('seat_count', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pickup_date', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pickup_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Routes', array(
             'local' => 'proposed_route_id',
             'foreign' => 'route_id'));

        $this->hasOne('SeatNegotiationStatuses', array(
             'local' => 'seat_negotiation_statuses_id',
             'foreign' => 'seat_negotiation_statuses_id'));

        $this->hasOne('Carpools', array(
             'local' => 'carpool_id',
             'foreign' => 'carpool_id'));

        $this->hasOne('Passengers', array(
             'local' => 'passenger_id',
             'foreign' => 'passenger_id'));

        $this->hasMany('SeatNegotiationMessage', array(
             'local' => 'seat_negotiation_id',
             'foreign' => 'seat_negotiation_id'));

        $this->hasMany('Seats', array(
             'local' => 'seat_negotiation_id',
             'foreign' => 'seat_negotiation_id'));
    }
}