<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeatRequestTypes', 'doctrine');

/**
 * BaseSeatRequestTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seat_request_type_id
 * @property string $display_text
 * @property string $slug
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Seats
 * 
 * @method integer             getSeatRequestTypeId()    Returns the current record's "seat_request_type_id" value
 * @method string              getDisplayText()          Returns the current record's "display_text" value
 * @method string              getSlug()                 Returns the current record's "slug" value
 * @method timestamp           getCreatedAt()            Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()            Returns the current record's "updated_at" value
 * @method Doctrine_Collection getSeats()                Returns the current record's "Seats" collection
 * @method SeatRequestTypes    setSeatRequestTypeId()    Sets the current record's "seat_request_type_id" value
 * @method SeatRequestTypes    setDisplayText()          Sets the current record's "display_text" value
 * @method SeatRequestTypes    setSlug()                 Sets the current record's "slug" value
 * @method SeatRequestTypes    setCreatedAt()            Sets the current record's "created_at" value
 * @method SeatRequestTypes    setUpdatedAt()            Sets the current record's "updated_at" value
 * @method SeatRequestTypes    setSeats()                Sets the current record's "Seats" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSeatRequestTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seat_request_types');
        $this->hasColumn('seat_request_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('display_text', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('slug', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Seats', array(
             'local' => 'seat_request_type_id',
             'foreign' => 'seat_request_type_id'));
    }
}