<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Notifications', 'doctrine');

/**
 * BaseNotifications
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $notification_id
 * @property string $display_text
 * @property string $slug
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $NotificationSettings
 * 
 * @method integer             getNotificationId()       Returns the current record's "notification_id" value
 * @method string              getDisplayText()          Returns the current record's "display_text" value
 * @method string              getSlug()                 Returns the current record's "slug" value
 * @method timestamp           getCreatedAt()            Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()            Returns the current record's "updated_at" value
 * @method Doctrine_Collection getNotificationSettings() Returns the current record's "NotificationSettings" collection
 * @method Notifications       setNotificationId()       Sets the current record's "notification_id" value
 * @method Notifications       setDisplayText()          Sets the current record's "display_text" value
 * @method Notifications       setSlug()                 Sets the current record's "slug" value
 * @method Notifications       setCreatedAt()            Sets the current record's "created_at" value
 * @method Notifications       setUpdatedAt()            Sets the current record's "updated_at" value
 * @method Notifications       setNotificationSettings() Sets the current record's "NotificationSettings" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotifications extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notifications');
        $this->hasColumn('notification_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('display_text', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NotificationSettings', array(
             'local' => 'notification_id',
             'foreign' => 'notification_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}