<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Seatrequests', 'doctrine');

/**
 * BaseSeatrequests
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idseatrequest
 * @property string $driverid
 * @property string $passengerid
 * @property timestamp $createdon
 * @property Profiles $Profiles
 * @property Profiles $Profiles_2
 * @property Doctrine_Collection $Negotiation
 * 
 * @method integer             getIdseatrequest() Returns the current record's "idseatrequest" value
 * @method string              getDriverid()      Returns the current record's "driverid" value
 * @method string              getPassengerid()   Returns the current record's "passengerid" value
 * @method timestamp           getCreatedon()     Returns the current record's "createdon" value
 * @method Profiles            getProfiles()      Returns the current record's "Profiles" value
 * @method Profiles            getProfiles2()     Returns the current record's "Profiles_2" value
 * @method Doctrine_Collection getNegotiation()   Returns the current record's "Negotiation" collection
 * @method Seatrequests        setIdseatrequest() Sets the current record's "idseatrequest" value
 * @method Seatrequests        setDriverid()      Sets the current record's "driverid" value
 * @method Seatrequests        setPassengerid()   Sets the current record's "passengerid" value
 * @method Seatrequests        setCreatedon()     Sets the current record's "createdon" value
 * @method Seatrequests        setProfiles()      Sets the current record's "Profiles" value
 * @method Seatrequests        setProfiles2()     Sets the current record's "Profiles_2" value
 * @method Seatrequests        setNegotiation()   Sets the current record's "Negotiation" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSeatrequests extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seatrequests');
        $this->hasColumn('idseatrequest', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('driverid', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('passengerid', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('createdon', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profiles', array(
             'local' => 'driverid',
             'foreign' => 'idprofile'));

        $this->hasOne('Profiles as Profiles_2', array(
             'local' => 'passengerid',
             'foreign' => 'idprofile'));

        $this->hasMany('Negotiation', array(
             'local' => 'idseatrequest',
             'foreign' => 'idseatrequest'));
    }
}