<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Attendingstatustype', 'doctrine');

/**
 * BaseAttendingstatustype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idattendingstatustype
 * @property string $status
 * @property Doctrine_Collection $TravelersAttendingEvent
 * 
 * @method integer             getIdattendingstatustype()   Returns the current record's "idattendingstatustype" value
 * @method string              getStatus()                  Returns the current record's "status" value
 * @method Doctrine_Collection getTravelersAttendingEvent() Returns the current record's "TravelersAttendingEvent" collection
 * @method Attendingstatustype setIdattendingstatustype()   Sets the current record's "idattendingstatustype" value
 * @method Attendingstatustype setStatus()                  Sets the current record's "status" value
 * @method Attendingstatustype setTravelersAttendingEvent() Sets the current record's "TravelersAttendingEvent" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseAttendingstatustype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attendingstatustype');
        $this->hasColumn('idattendingstatustype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TravelersAttendingEvent', array(
             'local' => 'idattendingstatustype',
             'foreign' => 'status'));
    }
}