<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Messagerecipients', 'doctrine');

/**
 * BaseMessagerecipients
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $messages_idmessages
 * @property string $travelers_idtraveler
 * @property Messages $Messages
 * @property Profiles $Profiles
 * 
 * @method integer           getMessagesIdmessages()   Returns the current record's "messages_idmessages" value
 * @method string            getTravelersIdtraveler()  Returns the current record's "travelers_idtraveler" value
 * @method Messages          getMessages()             Returns the current record's "Messages" value
 * @method Profiles          getProfiles()             Returns the current record's "Profiles" value
 * @method Messagerecipients setMessagesIdmessages()   Sets the current record's "messages_idmessages" value
 * @method Messagerecipients setTravelersIdtraveler()  Sets the current record's "travelers_idtraveler" value
 * @method Messagerecipients setMessages()             Sets the current record's "Messages" value
 * @method Messagerecipients setProfiles()             Sets the current record's "Profiles" value
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseMessagerecipients extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('messagerecipients');
        $this->hasColumn('messages_idmessages', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('travelers_idtraveler', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Messages', array(
             'local' => 'messages_idmessages',
             'foreign' => 'idmessages'));

        $this->hasOne('Profiles', array(
             'local' => 'travelers_idtraveler',
             'foreign' => 'idprofile'));
    }
}