<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Carpools', 'doctrine');

/**
 * BaseCarpools
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $carpool_id
 * @property integer $route_id
 * @property integer $vehicle_id
 * @property date $start_date
 * @property time $start_time
 * @property string $description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Routes $Routes
 * @property Vehicles $Vehicles
 * @property Doctrine_Collection $Drivers
 * @property Doctrine_Collection $SeatNegotiations
 * @property Doctrine_Collection $Seats
 * 
 * @method integer             getCarpoolId()        Returns the current record's "carpool_id" value
 * @method integer             getRouteId()          Returns the current record's "route_id" value
 * @method integer             getVehicleId()        Returns the current record's "vehicle_id" value
 * @method date                getStartDate()        Returns the current record's "start_date" value
 * @method time                getStartTime()        Returns the current record's "start_time" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method Routes              getRoutes()           Returns the current record's "Routes" value
 * @method Vehicles            getVehicles()         Returns the current record's "Vehicles" value
 * @method Doctrine_Collection getDrivers()          Returns the current record's "Drivers" collection
 * @method Doctrine_Collection getSeatNegotiations() Returns the current record's "SeatNegotiations" collection
 * @method Doctrine_Collection getSeats()            Returns the current record's "Seats" collection
 * @method Carpools            setCarpoolId()        Sets the current record's "carpool_id" value
 * @method Carpools            setRouteId()          Sets the current record's "route_id" value
 * @method Carpools            setVehicleId()        Sets the current record's "vehicle_id" value
 * @method Carpools            setStartDate()        Sets the current record's "start_date" value
 * @method Carpools            setStartTime()        Sets the current record's "start_time" value
 * @method Carpools            setDescription()      Sets the current record's "description" value
 * @method Carpools            setCreatedAt()        Sets the current record's "created_at" value
 * @method Carpools            setUpdatedAt()        Sets the current record's "updated_at" value
 * @method Carpools            setRoutes()           Sets the current record's "Routes" value
 * @method Carpools            setVehicles()         Sets the current record's "Vehicles" value
 * @method Carpools            setDrivers()          Sets the current record's "Drivers" collection
 * @method Carpools            setSeatNegotiations() Sets the current record's "SeatNegotiations" collection
 * @method Carpools            setSeats()            Sets the current record's "Seats" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCarpools extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carpools');
        $this->hasColumn('carpool_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('route_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vehicle_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('start_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('start_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Routes', array(
             'local' => 'route_id',
             'foreign' => 'route_id'));

        $this->hasOne('Vehicles', array(
             'local' => 'vehicle_id',
             'foreign' => 'vehicle_id'));

        $this->hasMany('Drivers', array(
             'local' => 'carpool_id',
             'foreign' => 'carpool_id'));

        $this->hasMany('SeatNegotiations', array(
             'local' => 'carpool_id',
             'foreign' => 'carpool_id'));

        $this->hasMany('Seats', array(
             'local' => 'carpool_id',
             'foreign' => 'carpool_id'));
    }
}