<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeatsFilledLegs', 'doctrine');

/**
 * BaseSeatsFilledLegs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seats_seat_id
 * @property integer $legs_leg_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Seats $Seats
 * @property Legs $Legs
 * 
 * @method integer         getSeatsSeatId()   Returns the current record's "seats_seat_id" value
 * @method integer         getLegsLegId()     Returns the current record's "legs_leg_id" value
 * @method timestamp       getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()     Returns the current record's "updated_at" value
 * @method Seats           getSeats()         Returns the current record's "Seats" value
 * @method Legs            getLegs()          Returns the current record's "Legs" value
 * @method SeatsFilledLegs setSeatsSeatId()   Sets the current record's "seats_seat_id" value
 * @method SeatsFilledLegs setLegsLegId()     Sets the current record's "legs_leg_id" value
 * @method SeatsFilledLegs setCreatedAt()     Sets the current record's "created_at" value
 * @method SeatsFilledLegs setUpdatedAt()     Sets the current record's "updated_at" value
 * @method SeatsFilledLegs setSeats()         Sets the current record's "Seats" value
 * @method SeatsFilledLegs setLegs()          Sets the current record's "Legs" value
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSeatsFilledLegs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seats_filled_legs');
        $this->hasColumn('seats_seat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('legs_leg_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Seats', array(
             'local' => 'seats_seat_id',
             'foreign' => 'seat_id'));

        $this->hasOne('Legs', array(
             'local' => 'legs_leg_id',
             'foreign' => 'leg_id'));
    }
}