<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Friendships', 'doctrine');

/**
 * BaseFriendships
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $friend1_id
 * @property integer $friend2_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property People $People
 * @property People $People_2
 * 
 * @method integer     getFriend1Id()  Returns the current record's "friend1_id" value
 * @method integer     getFriend2Id()  Returns the current record's "friend2_id" value
 * @method timestamp   getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()  Returns the current record's "updated_at" value
 * @method People      getPeople()     Returns the current record's "People" value
 * @method People      getPeople2()    Returns the current record's "People_2" value
 * @method Friendships setFriend1Id()  Sets the current record's "friend1_id" value
 * @method Friendships setFriend2Id()  Sets the current record's "friend2_id" value
 * @method Friendships setCreatedAt()  Sets the current record's "created_at" value
 * @method Friendships setUpdatedAt()  Sets the current record's "updated_at" value
 * @method Friendships setPeople()     Sets the current record's "People" value
 * @method Friendships setPeople2()    Sets the current record's "People_2" value
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriendships extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friendships');
        $this->hasColumn('friend1_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('friend2_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('People', array(
             'local' => 'friend1_id',
             'foreign' => 'person_id'));

        $this->hasOne('People as People_2', array(
             'local' => 'friend2_id',
             'foreign' => 'person_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}