<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SeatNegotiationMessage', 'doctrine');

/**
 * BaseSeatNegotiationMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seat_negotiation_message_id
 * @property integer $seat_negotiation_id
 * @property integer $author_id
 * @property string $message
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property SeatNegotiations $SeatNegotiations
 * @property People $People
 * 
 * @method integer                getSeatNegotiationMessageId()    Returns the current record's "seat_negotiation_message_id" value
 * @method integer                getSeatNegotiationId()           Returns the current record's "seat_negotiation_id" value
 * @method integer                getAuthorId()                    Returns the current record's "author_id" value
 * @method string                 getMessage()                     Returns the current record's "message" value
 * @method timestamp              getCreatedAt()                   Returns the current record's "created_at" value
 * @method timestamp              getUpdatedAt()                   Returns the current record's "updated_at" value
 * @method SeatNegotiations       getSeatNegotiations()            Returns the current record's "SeatNegotiations" value
 * @method People                 getPeople()                      Returns the current record's "People" value
 * @method SeatNegotiationMessage setSeatNegotiationMessageId()    Sets the current record's "seat_negotiation_message_id" value
 * @method SeatNegotiationMessage setSeatNegotiationId()           Sets the current record's "seat_negotiation_id" value
 * @method SeatNegotiationMessage setAuthorId()                    Sets the current record's "author_id" value
 * @method SeatNegotiationMessage setMessage()                     Sets the current record's "message" value
 * @method SeatNegotiationMessage setCreatedAt()                   Sets the current record's "created_at" value
 * @method SeatNegotiationMessage setUpdatedAt()                   Sets the current record's "updated_at" value
 * @method SeatNegotiationMessage setSeatNegotiations()            Sets the current record's "SeatNegotiations" value
 * @method SeatNegotiationMessage setPeople()                      Sets the current record's "People" value
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSeatNegotiationMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seat_negotiation_message');
        $this->hasColumn('seat_negotiation_message_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('seat_negotiation_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('author_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SeatNegotiations', array(
             'local' => 'seat_negotiation_id',
             'foreign' => 'seat_negotiation_id'));

        $this->hasOne('People', array(
             'local' => 'author_id',
             'foreign' => 'person_id'));
    }
}