<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rideofferposts', 'doctrine');

/**
 * BaseRideofferposts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idrideofferpost
 * @property string $travelers_idusers
 * @property float $price
 * @property integer $numberofseats
 * @property date $date
 * @property time $time
 * @property string $comments
 * @property integer $origin
 * @property integer $destination
 * @property integer $vehicles_idvehicle
 * @property Profiles $Profiles
 * @property Locations $Locations
 * @property Locations $Locations_3
 * @property Vehicles $Vehicles
 * @property Doctrine_Collection $Waypoints
 * 
 * @method integer             getIdrideofferpost()    Returns the current record's "idrideofferpost" value
 * @method string              getTravelersIdusers()   Returns the current record's "travelers_idusers" value
 * @method float               getPrice()              Returns the current record's "price" value
 * @method integer             getNumberofseats()      Returns the current record's "numberofseats" value
 * @method date                getDate()               Returns the current record's "date" value
 * @method time                getTime()               Returns the current record's "time" value
 * @method string              getComments()           Returns the current record's "comments" value
 * @method integer             getOrigin()             Returns the current record's "origin" value
 * @method integer             getDestination()        Returns the current record's "destination" value
 * @method integer             getVehiclesIdvehicle()  Returns the current record's "vehicles_idvehicle" value
 * @method Profiles            getProfiles()           Returns the current record's "Profiles" value
 * @method Locations           getLocations()          Returns the current record's "Locations" value
 * @method Locations           getLocations3()         Returns the current record's "Locations_3" value
 * @method Vehicles            getVehicles()           Returns the current record's "Vehicles" value
 * @method Doctrine_Collection getWaypoints()          Returns the current record's "Waypoints" collection
 * @method Rideofferposts      setIdrideofferpost()    Sets the current record's "idrideofferpost" value
 * @method Rideofferposts      setTravelersIdusers()   Sets the current record's "travelers_idusers" value
 * @method Rideofferposts      setPrice()              Sets the current record's "price" value
 * @method Rideofferposts      setNumberofseats()      Sets the current record's "numberofseats" value
 * @method Rideofferposts      setDate()               Sets the current record's "date" value
 * @method Rideofferposts      setTime()               Sets the current record's "time" value
 * @method Rideofferposts      setComments()           Sets the current record's "comments" value
 * @method Rideofferposts      setOrigin()             Sets the current record's "origin" value
 * @method Rideofferposts      setDestination()        Sets the current record's "destination" value
 * @method Rideofferposts      setVehiclesIdvehicle()  Sets the current record's "vehicles_idvehicle" value
 * @method Rideofferposts      setProfiles()           Sets the current record's "Profiles" value
 * @method Rideofferposts      setLocations()          Sets the current record's "Locations" value
 * @method Rideofferposts      setLocations3()         Sets the current record's "Locations_3" value
 * @method Rideofferposts      setVehicles()           Sets the current record's "Vehicles" value
 * @method Rideofferposts      setWaypoints()          Sets the current record's "Waypoints" collection
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRideofferposts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rideofferposts');
        $this->hasColumn('idrideofferpost', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('travelers_idusers', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('numberofseats', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('comments', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('origin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('destination', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('vehicles_idvehicle', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profiles', array(
             'local' => 'travelers_idusers',
             'foreign' => 'idprofile'));

        $this->hasOne('Locations', array(
             'local' => 'origin',
             'foreign' => 'idlocation'));

        $this->hasOne('Locations as Locations_3', array(
             'local' => 'destination',
             'foreign' => 'idlocation'));

        $this->hasOne('Vehicles', array(
             'local' => 'vehicles_idvehicle',
             'foreign' => 'idvehicle'));

        $this->hasMany('Waypoints', array(
             'local' => 'idrideofferpost',
             'foreign' => 'rideofferposts_idrideofferpost'));
    }
}