<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('seats', 'ssss_1');
    }

    public function down()
    {
        $this->createForeignKey('seats', 'ssss_1', array(
             'name' => 'ssss_1',
             'local' => 'seat_request_type_id',
             'foreign' => 'seat_request_type_id',
             'foreignTable' => 'seat_request_types',
             ));
    }
}