<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('locations', 'location_id', 'integer', '5', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '1',
             'autoincrement' => '1',
             ));
    }

    public function down()
    {
        $this->changeColumn('locations', 'location_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '1',
             'autoincrement' => '1',
             ));
    }
}