<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('comments', 'comments_event_id_events_event_id');
        $this->dropForeignKey('comments', 'comments_person_id_people_person_id');
        $this->dropForeignKey('events', 'events_location_id_locations_location_id');
        $this->dropForeignKey('friendship_requests', 'friendship_requests_requestor_id_people_person_id');
        $this->dropForeignKey('friendship_requests', 'friendship_requests_requestee_id_people_person_id');
        $this->dropForeignKey('friendship_requests', 'ffff');
        $this->dropForeignKey('friendships', 'friendships_friend1_id_people_person_id');
        $this->dropForeignKey('friendships', 'friendships_friend2_id_people_person_id');
        $this->dropForeignKey('security_settings', 'security_settings_person_id_people_person_id');
        $this->dropForeignKey('travelers_attending_event', 'travelers_attending_event_event_id_events_event_id');
        $this->dropForeignKey('travelers_attending_event', 'tsaa');
        $this->dropForeignKey('travelers_attending_event', 'travelers_attending_event_person_id_people_person_id');
        $this->dropForeignKey('users', 'users_person_id_people_person_id');
    }

    public function down()
    {
        $this->createForeignKey('comments', 'comments_event_id_events_event_id', array(
             'name' => 'comments_event_id_events_event_id',
             'local' => 'event_id',
             'foreign' => 'event_id',
             'foreignTable' => 'events',
             ));
        $this->createForeignKey('comments', 'comments_person_id_people_person_id', array(
             'name' => 'comments_person_id_people_person_id',
             'local' => 'person_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('events', 'events_location_id_locations_location_id', array(
             'name' => 'events_location_id_locations_location_id',
             'local' => 'location_id',
             'foreign' => 'location_id',
             'foreignTable' => 'locations',
             ));
        $this->createForeignKey('friendship_requests', 'friendship_requests_requestor_id_people_person_id', array(
             'name' => 'friendship_requests_requestor_id_people_person_id',
             'local' => 'requestor_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('friendship_requests', 'friendship_requests_requestee_id_people_person_id', array(
             'name' => 'friendship_requests_requestee_id_people_person_id',
             'local' => 'requestee_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('friendship_requests', 'ffff', array(
             'name' => 'ffff',
             'local' => 'friendship_status_id',
             'foreign' => 'friendship_status_id',
             'foreignTable' => 'friendship_statuses',
             ));
        $this->createForeignKey('friendships', 'friendships_friend1_id_people_person_id', array(
             'name' => 'friendships_friend1_id_people_person_id',
             'local' => 'friend1_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('friendships', 'friendships_friend2_id_people_person_id', array(
             'name' => 'friendships_friend2_id_people_person_id',
             'local' => 'friend2_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('security_settings', 'security_settings_person_id_people_person_id', array(
             'name' => 'security_settings_person_id_people_person_id',
             'local' => 'person_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('travelers_attending_event', 'travelers_attending_event_event_id_events_event_id', array(
             'name' => 'travelers_attending_event_event_id_events_event_id',
             'local' => 'event_id',
             'foreign' => 'event_id',
             'foreignTable' => 'events',
             ));
        $this->createForeignKey('travelers_attending_event', 'tsaa', array(
             'name' => 'tsaa',
             'local' => 'status',
             'foreign' => 'attending_status_type_id',
             'foreignTable' => 'attending_status_type',
             ));
        $this->createForeignKey('travelers_attending_event', 'travelers_attending_event_person_id_people_person_id', array(
             'name' => 'travelers_attending_event_person_id_people_person_id',
             'local' => 'person_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->createForeignKey('users', 'users_person_id_people_person_id', array(
             'name' => 'users_person_id_people_person_id',
             'local' => 'person_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
    }
}