<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version55 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('routes', 'origin_address', 'string', '255', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'origin_city', 'string', '45', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'origin_state', 'string', '2', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'origin_latitude', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'origin_longitude', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'destination_address', 'string', '255', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'destination_city', 'string', '45', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'destination_state', 'string', '2', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'destination_latitude', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'destination_longitude', 'float', '', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'distance', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('routes', 'duration', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('routes', 'origin_address');
        $this->removeColumn('routes', 'origin_city');
        $this->removeColumn('routes', 'origin_state');
        $this->removeColumn('routes', 'origin_latitude');
        $this->removeColumn('routes', 'origin_longitude');
        $this->removeColumn('routes', 'destination_address');
        $this->removeColumn('routes', 'destination_city');
        $this->removeColumn('routes', 'destination_state');
        $this->removeColumn('routes', 'destination_latitude');
        $this->removeColumn('routes', 'destination_longitude');
        $this->removeColumn('routes', 'distance');
        $this->removeColumn('routes', 'duration');
    }
}