<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version52 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('sf_guard_user', 'sf_guard_user_person_id_people_person_id');
    }

    public function down()
    {
        $this->createForeignKey('sf_guard_user', 'sf_guard_user_person_id_people_person_id', array(
             'name' => 'sf_guard_user_person_id_people_person_id',
             'local' => 'person_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
    }
}