<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('notification_settings', 'nnnn', array(
             'name' => 'nnnn',
             'local' => 'notification_id',
             'foreign' => 'notification_id',
             'foreignTable' => 'notifications',
             ));
        $this->createForeignKey('notification_settings', 'notification_settings_person_id_people_person_id', array(
             'name' => 'notification_settings_person_id_people_person_id',
             'local' => 'person_id',
             'foreign' => 'person_id',
             'foreignTable' => 'people',
             ));
        $this->addIndex('notification_settings', 'notification_settings_notification_id', array(
             'fields' => 
             array(
              0 => 'notification_id',
             ),
             ));
        $this->addIndex('notification_settings', 'notification_settings_person_id', array(
             'fields' => 
             array(
              0 => 'person_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('notification_settings', 'nnnn');
        $this->dropForeignKey('notification_settings', 'notification_settings_person_id_people_person_id');
        $this->removeIndex('notification_settings', 'notification_settings_notification_id', array(
             'fields' => 
             array(
              0 => 'notification_id',
             ),
             ));
        $this->removeIndex('notification_settings', 'notification_settings_person_id', array(
             'fields' => 
             array(
              0 => 'person_id',
             ),
             ));
    }
}