<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version64 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('routes', 'origin_place_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'autoincrement' => '',
             'notnull' => '',
             ));
        $this->addColumn('routes', 'destination_place_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'autoincrement' => '',
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('routes', 'origin_place_id');
        $this->removeColumn('routes', 'destination_place_id');
    }
}