<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version70 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('places', 'places_location_id_locations_location_id', array(
             'name' => 'places_location_id_locations_location_id',
             'local' => 'location_id',
             'foreign' => 'location_id',
             'foreignTable' => 'locations',
             ));
        $this->addIndex('places', 'places_location_id', array(
             'fields' => 
             array(
              0 => 'location_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('places', 'places_location_id_locations_location_id');
        $this->removeIndex('places', 'places_location_id', array(
             'fields' => 
             array(
              0 => 'location_id',
             ),
             ));
    }
}