<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version76 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('events', 'place_id', 'integer', '4', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'autoincrement' => '',
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('events', 'place_id');
    }
}