<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version80 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('events', 'share_image_url', 'string', '255', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
        $this->addColumn('places', 'share_image_url', 'string', '255', array(
             'fixed' => '0',
             'unsigned' => '',
             'primary' => '',
             'notnull' => '',
             'autoincrement' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('events', 'share_image_url');
        $this->removeColumn('places', 'share_image_url');
    }
}