<?php

/**
 * AttendingStatusTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AttendingStatusTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AttendingStatusTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AttendingStatusType');
    }
}