<?php

/**
 * ConversationParticipantsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConversationParticipantsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConversationParticipantsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConversationParticipants');
    }
}