<?php

/**
 * DriversTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DriversTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DriversTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Drivers');
    }
}