<?php

/**
 * EventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Events');
    }
    public function getPartnerEvents()
    {

        $q = $this->createQuery('e')
                ->where('e.isPartner = 1')
                ->andWhere('e.is_deleted != 1');
        return $q->execute();
    }
    public function getEvents(){
                $q = $this->createQuery('e')
                ->where('e.is_deleted != 1');
        return $q->execute();
    }
}