<?php

/**
 * FriendshipStatusesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FriendshipStatusesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FriendshipStatusesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FriendshipStatuses');
    }
}