<?php

/**
 * Friendships
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Friendships extends BaseFriendships
{
    public function getFriendshipStatus($personID)
    {
        $myId = sfContext::getInstance()->getUser()->getGuardUser()->getPersonId();

        // Need sql to match this query
        // select * from friendship_requests fr
        // where fr.requestor_id = 1 and fr.requestee_id = 2
        //    or fr.requestee_id = 1 and fr.requestor_id = 2;
        $q = Doctrine_Query::create()
                ->select('friendship_status_id')
                ->from('friendship_requests fr')
                ->where('fr.requestor_id = ? AND fr.requestee_id = ?', array($myId, $personID))
                ->orWhere('fr.requestee_id = ? AND fr.requestor_id = ?', array($myId, $personID));

        // Return a boolean indicating whether there was a friendship
        // record found.
        return $q->execute();
    }
}