<?php

/**
 * MessageRecipientsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageRecipientsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MessageRecipientsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MessageRecipients');
    }
}