<?php

/**
 * Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Messages extends BaseMessages
{
    public function getBodyPreview($length = 40) {
        return substr($this->getBody(), 0, $length);
    }

    public function isUnread() {
        // Create the return value
        $isUnread = false;

        if (sfContext::getInstance()->getUser()->isAuthenticated())
        {
            // Get the authenticated user's personId
            $myId = sfContext::getInstance()->getUser()->getGuardUser()->getPersonId();

            // Check to see if the message is unread for the user
            $myRecipientInfo = null;
            //$myRecipientInfo = $this->getMessageRecipients()->get(array("message_id" => $this->getMessageId(), "person_id" => $myId));
            if ($myRecipientInfo != null)
            {
               $isUnread = $myRecipientInfo->getUnread();
            }
        }

        return $isUnread;
    }

}