<?php

/**
 * Messages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Messages extends BaseMessages
{
    public function getBodyPreview($length = 40) {
        return substr($this->getBody(), 0, $length);
    }

}