<?php

/**
 * NotificationSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificationSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotificationSettings');
    }
}