<?php

/**
 * PassengersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PassengersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     * @return object PassengersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Passengers');
    }

    /**
     * Gets all passengers with profiles
     * @return Doctrine_Collection The passengers with profiles 
     */
    public function getWithProfiles()
    {
        $q = $this->createQuery('c')
          ->leftJoin('c.People p')
          ->leftJoin('p.Profiles pr');;

        return $q->execute();
    }
    
    /**
     * Returns all passenger record for the authenticated user
     * @return Doctrine_Collection Returns a passengers collection for the user
     */
    public function getMyPassengers()
    {
        // Create the return value
        $passengers = null;

        if (sfContext::getInstance()->getUser()->isAuthenticated())
        {
            // Get the authenticated user's personId
            $myId = sfContext::getInstance()->getUser()->getGuardUser()->getPersonId();
            $passengers = $this->getPassengersForPerson($myId);
        }

        return $passengers;
    }


    /**
     * Returns all passenger records for a person
     * @param int $personId The person to get the passengers for
     * @return Doctrine_Collection Returns a Passengers collection
     */
    public function getPassengersForPerson($personId)
    {
        $q = $this->createQuery('p')
          ->where('p.person_id = ?', array($personId));

        return $q->execute();
    }
}