<?php

/**
 * Passengers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Passengers extends BasePassengers
{
    /**
     * Returns a string that represents the passenger. Overrides the default
     * __toString method.
     * @return string The passenger represented as a string
     */
    public function __toString()
    {
        $passengerName = "";

        $passengerName = $this->getPassengerId() . " - " . $this->getStartDate();

        return $passengerName;

    }
}