<?php

/**
 * PlacesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlacesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlacesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Places');
    }
}