<?php

/**
 * Profiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Profiles extends BaseProfiles
{
    public function getFullName()
    {
        $fullName = $this->getFirstName();
        if ($this->getFirstName() != null && $this->getLastName() != null)
        {
            $fullName = $fullName . " ";
        }
        $fullName = $fullName . $this->getLastName();
        return $fullName;
    }

    public function getFriendsProfiles()
    {
        // Is this the correct place for this???
        //use this SQL statement as a reference
        // select * from profiles pr, friendships f where (pr.person_id = f.friend1_id and f.friend2_id = 1) or (pr.person_id = f.friend2_id and f.friend1_id = 1);
    }
}