<?php

/**
 * SeatNegotiationMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatNegotiationMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatNegotiationMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatNegotiationMessage');
    }
}