<?php

/**
 * Seats
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Seats extends BaseSeats
{
    /**
     * Gets the origin location for a route
     * @return Locations The origin
     */
    public function getOriginLocation()
    {
        $first_location = $this->getRoutes()->getOriginLocation();

        return $first_location;
    }

    /**
     * Gets the destination location for a route
     * @return Locations The destination
     */
    public function getDestinationLocation()
    {
        $last_location = $this->getRoutes()->getDestinationLocation();

        return $last_location;
    }
    
    /**
     * Saves the seat and saves the schange into the history log
     * @param int $personId
     * @param Doctrine_Connection $conn THe doctrine connection
     * @return Seats The saved seat
     */
    public function saveWithHistory($personId, Doctrine_Connection $conn = null)
    {
        // Get the connection information
        $conn = $conn ? $conn : $this->getTable()->getConnection();
        // Begin a transaction so it can be rolled back if something goes
        // wrong
        $conn->beginTransaction();
        try
        {
            // Get the is new value since it will change after saving
            $isNew = $this->isNew();

            // If the seat is new, set the status to be pending
            if ($isNew)
            {
                $pendingStatusId = SeatStatusesTable::getInstance()->findOneBy('slug', 'pending')->getSeatStatusId();
                $this->setSeatStatusId($pendingStatusId);
            }
            
            // Save the seat
            $ret = parent::save($conn);

            // Commit the transaction
            $conn->commit();

            return $ret;
        }
        catch (Exception $e)
        {
            $conn->rollBack();
            throw $e;
        }
    }

}