<?php

/**
 * SeatneededpostsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatneededpostsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatneededpostsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seatneededposts');
    }
}