<?php

/**
 * SeatStatusesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatStatusesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatStatusesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatStatuses');
    }
}