<?php

/**
 * SeatStatusesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatStatusesTable extends Doctrine_Table
{
    /**
     * The supported seat status types. This is a shortcut instead of
     * querying the database.
     * @var string The seat status type
     */
    public static $rideTypes = array('pending' => 1,
                                     'accepted' => 2,
                                     'declined' => 3,
                                     'recommended' => 4);
    
    /**
     * Gets the displayable name string of the seat status
     * @param int $seatStatusId The status id
     * @return String The displayable name of the status 
     */
    public static function getStatusString($seatStatusId)
    {
        return array_search($seatStatusId, SeatStatusesTable::$rideTypes); 
    }

    /**
     * Returns an instance of this class.
     *
     * @return object SeatStatusesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatStatuses');
    }
}