<?php

/**
 * SeatNegotiationStatusesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatNegotiationStatusesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatNegotiationStatusesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatNegotiationStatuses');
    }
}