<?php

/**
 * SeatsFilledLegsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeatsFilledLegsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeatsFilledLegsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SeatsFilledLegs');
    }
}