<?php

/**
 * SeatsHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RootlessMe
 * @subpackage model
 * @author     awilliams
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SeatsHistory extends BaseSeatsHistory
{
    /**
     * Creates a seat history record based on a seat
     * @param Seats $seat The seat to create a history record for
     * @param int $personId The person id of the changer
     * @param string $action The action for the history. 'update' is the
     * default.
     * @return SeatsHistory The histroy created for the seat
     */
    public static function createHistoryFromSeat($seat, $personId , $action='update') {
        // Creeate the new seat history entry
        $seatHistoryEntry = new SeatsHistory();
        
        // Set all of the properties in the seat history entry based on the 
        // seat
        $seatHistoryEntry->setSeatId($seat->getSeatId());
        $seatHistoryEntry->setCarpoolId($seat->getCarpoolId());
        $seatHistoryEntry->setPassengerId($seat->getPassengerId());
        $seatHistoryEntry->setSeatStatusId($seat->getSeatStatusId());
        $seatHistoryEntry->setSoloRouteId($seat->getSoloRouteId());
        $seatHistoryEntry->setPrice($seat->getPrice());
        $seatHistoryEntry->setSeatCount($seat->getSeatCount());
        $seatHistoryEntry->setPickupDate($seat->getPickupDate());
        $seatHistoryEntry->setPickupTime($seat->getPickupTime());
        $seatHistoryEntry->setDescription($seat->getDescription());
        $seatHistoryEntry->setChangerId($personId);
        $seatHistoryEntry->setChangeAction($action);
//        $seatHistoryEntry->setPeople($user);
        $seatHistoryEntry->setSeats($seat);
        
        return $seatHistoryEntry;
    }
}
