<?php

/**
 * SecuritySettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecuritySettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SecuritySettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SecuritySettings');
    }
}