<?php

/**
 * SecuritysettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecuritysettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SecuritysettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Securitysettings');
    }
}