<?php

/**
 * VehiclesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiclesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiclesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vehicles');
    }
}