# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# static pages rules
home:
  url: /home
  param:
    module: static
    action: home

# profile rules
profile:
  url: /profiles
  class:   sfDoctrineRoute
  param:
    module: profile
    action: index
  options:
    model: Profiles
    type: list
  requirements:
    sf_method: [get]

profile_new_user:
  url:   /profiles/new
  class:   sfDoctrineRoute
  options: { model: Profiles, type: object }
  param: { module: profile, action: new }
  requirements:
    sf_method: [get]
    
profile_create_user:
  url:   /profiles/create
  class:   sfDoctrineRoute
  options: { model: Profiles, type: object }
  param: { module: profile, action: create }
  requirements:
    sf_method: [post]

profile_edit_user:
  url:   /profiles/edit
  class:   sfDoctrineRoute
  options: { model: Profiles, type: object }
  param: { module: profile, action: edit }
  requirements:
    sf_method: [get]

profile_update_user:
  url:   /profiles/update
  class:   sfDoctrineRoute
  options: { model: Profiles, type: object }
  param: { module: profile, action: update }
  requirements:
    sf_method: [post]
    
profile_show_user:
  url:   /profiles/:profile_name
  class:   sfDoctrineRoute
  options: { model: Profiles, type: object }
  param: { module: profile, action: show }
  requirements:
    sf_method: [get]


# message rules
messages:
  url: /messages
  class:   sfDoctrineRouteCollection
  param:
    module: message
    action: index
  options:
    model: Messages

messages_show:
  url:   /messages/:conversation_id/:message_id
  class:   sfDoctrineRoute
  options: { model: Messages, type: object }
  param: { module: message, action: show }
  requirements:
    sf_method: [get]

messages_edit:
  url:   /messages/edit/:conversation_id/:message_id
  class:   sfDoctrineRoute
  options: { model: Messages, type: object }
  param: { module: message, action: edit }
  requirements:
    sf_method: [get]

conversations:
  url: /conversations
  class:   sfDoctrineRoute
  param:
    module: conversation
    action: index
  options:
    model: Conversations
    type: list
  requirements:
    sf_method: [get]

conversations_show:
  url:   /conversations/:conversation_id
  class:   sfDoctrineRoute
  options: { model: Conversations, type: object }
  param: { module: conversation, action: show }
  requirements:
    sf_method: [get]

# sfGuard routes
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_register:
  url:   /register
  param: { module: sfGuardRegister, action: index }

# ride rules
ride:
  url: /rides
  param:
    module: ride
    action: index

ride_search:
  url: /rides/search
  param: { module: ride, action: search, sf_format: html }
  requirements:
    sf_format: (?:html)
    
ride_offer_new:
  url: /rides/offers/new
  class:   sfDoctrineRoute
  param:
    module: ride
    action: newOffer
  options:
    model: Carpools
    type: object
  requirements:
    sf_method: [get]

ride_offer_create:
  url: /rides/offers/create
  class:   sfDoctrineRoute
  param:
    module: ride
    action: createOffer
  options:
    model: Carpools
    type: object
  requirements:
    sf_method: [post]

ride_offer_update:
  url: /rides/offers/update
  class:   sfDoctrineRoute
  param:
    module: ride
    action: updateOffer
  options:
    model: Carpools
    type: object
  requirements:
    sf_method: [post]

ride_offer:
  url: /rides/offers/:carpool_id
  class:   sfDoctrineRoute
  param:
    module: ride
    action: showOffer
  options:
    model: Carpools
    type: object
  requirements:
    sf_method: [get]




# default rules
homepage:
  url:   /
  param: { module: static, action: home }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
