<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/31 10:08:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=RootlessMeDev',
  'username' => 'aawillia',
  'password' => 'buddyb33',
  'name' => 'doctrine',
)),);
